### ISSUE TITLE
initial order book generation

### ISSUE THREAD

**Issue by Firescar96** [metalicjames/mmbot#3]
https://github.com/metalicjames/mmbot/blob/31feff2ed279f3b473769a1090695e7c5d0234e1/book.go#L58

Is the inclusion of `start` a typo? I discovered then when creating a market with sia where all values in the config are on the order of 1e-7

**Comment by metalicjames** [comment]
It's not a typo. Interval is the proportion of the start value to change each order by rather than an absolute price differential.

**Comment by Firescar96** [comment]
I see. I was having trouble finding a good value for siacoin, I actually do want it to be a constant 1 wei per trade there.

**Comment by Firescar96** [comment]
GAH! Poloniex api rounds terribly. If i pass a rate of more than 8 decimal places it rounds to .000001, but with 8 decimal places exactly it allows values of .00000074 and such.
